#!/usr/bin/env node
/**
 * Single source of version for web, Android and iOS.
 *
 *   node scripts/version.mjs show
 *   node scripts/version.mjs bump patch|minor|major
 *   node scripts/version.mjs set 1.2.0
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

export const VERSION_REL = "version.json";

export function projectRoot(from = fileURLToPath(import.meta.url)) {
  return dirname(dirname(from));
}

export function parseSemver(value) {
  const match = String(value ?? "").trim().match(/^(\d+)\.(\d+)\.(\d+)$/);
  if (!match) return { error: `not a semver X.Y.Z: ${value}` };
  return {
    major: Number(match[1]),
    minor: Number(match[2]),
    patch: Number(match[3]),
  };
}

export function formatSemver({ major, minor, patch }) {
  return `${major}.${minor}.${patch}`;
}

export function bumpSemver(version, part) {
  const parsed = parseSemver(version);
  if (parsed.error) return parsed;
  if (part === "major") return formatSemver({ major: parsed.major + 1, minor: 0, patch: 0 });
  if (part === "minor") return formatSemver({ major: parsed.major, minor: parsed.minor + 1, patch: 0 });
  if (part === "patch") return formatSemver({ major: parsed.major, minor: parsed.minor, patch: parsed.patch + 1 });
  return { error: `unknown bump: ${part} (use patch, minor or major)` };
}

export function readVersionDoc(root) {
  const raw = JSON.parse(readFileSync(join(root, VERSION_REL), "utf8"));
  const parsed = parseSemver(raw.version);
  if (parsed.error) throw new Error(parsed.error);
  const versionCode = Number(raw.versionCode);
  if (!Number.isInteger(versionCode) || versionCode < 1) {
    throw new Error(`versionCode must be a positive integer, got ${raw.versionCode}`);
  }
  return {
    name: typeof raw.name === "string" ? raw.name : "מעקב צירים",
    version: raw.version,
    versionCode,
  };
}

export function nextVersion(doc, action, value) {
  if (action === "set") {
    const parsed = parseSemver(value);
    if (parsed.error) return parsed;
    return {
      ...doc,
      version: formatSemver(parsed),
      versionCode: doc.versionCode + 1,
    };
  }
  if (action === "bump") {
    const version = bumpSemver(doc.version, value);
    if (typeof version !== "string") return version;
    return { ...doc, version, versionCode: doc.versionCode + 1 };
  }
  return { error: `unknown action: ${action}` };
}

function writeJson(path, value) {
  writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`);
}

export function applyVersion(root, doc) {
  writeJson(join(root, VERSION_REL), {
    name: doc.name,
    version: doc.version,
    versionCode: doc.versionCode,
  });

  const packagePath = join(root, "package.json");
  const pkg = JSON.parse(readFileSync(packagePath, "utf8"));
  pkg.version = doc.version;
  writeJson(packagePath, pkg);

  writeFileSync(
    join(root, "src/lib/app-version.ts"),
    [
      "/** Generated by scripts/version.mjs — do not edit by hand. */",
      `export const APP_VERSION = ${JSON.stringify(doc.version)};`,
      `export const APP_VERSION_CODE = ${doc.versionCode};`,
      "",
    ].join("\n"),
  );

  const pbx = join(root, "ios/App/App.xcodeproj/project.pbxproj");
  let pbxText = readFileSync(pbx, "utf8");
  pbxText = pbxText.replace(/CURRENT_PROJECT_VERSION = \d+;/g, `CURRENT_PROJECT_VERSION = ${doc.versionCode};`);
  pbxText = pbxText.replace(/MARKETING_VERSION = [^;]+;/g, `MARKETING_VERSION = ${doc.version};`);
  writeFileSync(pbx, pbxText);

  stampChangelog(join(root, "CHANGELOG.md"), doc.version);
  return doc;
}

export function stampChangelog(path, version, today = isoDate()) {
  let text = "";
  try {
    text = readFileSync(path, "utf8");
  } catch {
    text = "# Changelog\n\n## Unreleased\n\n";
  }
  const heading = `## ${version} — ${today}`;
  if (text.includes(`## ${version} —`) || text.includes(`## ${version}\n`)) return text;
  if (/^## Unreleased\s*$/m.test(text)) {
    text = text.replace(/^## Unreleased\s*$/m, `## Unreleased\n\n${heading}\n`);
  } else {
    text = text.replace(/^# Changelog\s*$/m, `# Changelog\n\n## Unreleased\n\n${heading}`);
  }
  writeFileSync(path, text.endsWith("\n") ? text : `${text}\n`);
  return text;
}

export function isoDate(now = new Date()) {
  return now.toISOString().slice(0, 10);
}

export function parseVersionArgs(argv) {
  const args = argv.filter((item) => item !== "--");
  const action = args[0];
  if (action === "show") {
    if (args.length !== 1) return { error: "usage: version.mjs show" };
    return { action: "show" };
  }
  if (action === "bump") {
    if (args.length !== 2 || !["patch", "minor", "major"].includes(args[1])) {
      return { error: "usage: version.mjs bump patch|minor|major" };
    }
    return { action: "bump", value: args[1] };
  }
  if (action === "set") {
    if (args.length !== 2) return { error: "usage: version.mjs set X.Y.Z" };
    return { action: "set", value: args[1] };
  }
  return { error: "usage: version.mjs show | bump patch|minor|major | set X.Y.Z" };
}

function main() {
  const parsed = parseVersionArgs(process.argv.slice(2));
  if (parsed.error) {
    console.error(parsed.error);
    process.exitCode = 1;
    return;
  }
  const root = projectRoot();
  const current = readVersionDoc(root);
  if (parsed.action === "show") {
    process.stdout.write(`${current.version} (${current.versionCode})\n`);
    return;
  }
  const next = nextVersion(current, parsed.action, parsed.value);
  if (next.error) {
    console.error(next.error);
    process.exitCode = 1;
    return;
  }
  applyVersion(root, next);
  process.stdout.write(`${next.version} (${next.versionCode})\n`);
}

if (import.meta.url === `file://${process.argv[1]}`) main();
